version: "3.9"

services:
  campaign-service:
    build: ./campaign-service
    ports:
      - "3001:3001"
    env_file:
      - ./campaign-service/.env

  pdf-ranking-service:
    build: ./pdf-ranking-service
    ports:
      - "3002:3002"
    env_file:
      - ./pdf-ranking-service/.env

  analytics-service:
    build: ./analytics-service
    ports:
      - "3003:3003"
    env_file:
      - ./analytics-service/.env

  subscription-service:
    build: ./subscription-service
    ports:
      - "3004:3004"
    env_file:
      - ./subscription-service/.env